//
//  ViewController.swift
//  DMSOpenPGP
//
//  Created by CMK on 05/30/2019.
//  Copyright (c) 2019 CMK. All rights reserved.
//

import UIKit
import DMSOpenPGP

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.

        let keyData = GenerateKeyData(name: "Hello", email: "hello@word.pgp", password: "HelloWorldPGP", masterKey: KeyData(), subkey: KeyData())
        do {
            let keyRing = try DMSPGPKeyRingFactory(generateKeyData: keyData).keyRing

            print(keyRing.publicKeyRing.armored())
            // -----BEGIN PGP PUBLIC KEY BLOCK-----
            // Comment: Generated by DMSOpenPGP
            //
            // …
            // -----END PGP PUBLIC KEY BLOCK-----

        } catch {
            print(error.localizedDescription)
        }
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

}
