//
//  ViewController.swift
//  DMSOpenPGP
//
//  Created by CMK on 05/30/2019.
//  Copyright (c) 2019 CMK. All rights reserved.
//

import UIKit
import DMSOpenPGP

class ViewController: UIViewController {
    
    private let message = """
-----BEGIN PGP MESSAGE-----

hH4DAAAAAAAAAAASAgMECARcH2/pSm7AzYlXj1e2AySoM4C6JoF1UAR4Ot6MfIaM
M7GVwRi41PdqIA4dsp98B6kxyV3HUv01RA2fBgx9FTA2t0RVFm44rr4Mett6QUTg
31eFJsFpjJ5sJzcaP69NE+mu13M9+GumNOM59/rcakjSQQFvhZD1yNgHtWpQmMu7
ZgrPJ/IDy+7tc3QuQkPzK/zg1oPAvIq5PGW90LS1MVtjBGXwsQ2hUdFdHVZ1paSb
IDEG
=Dv1Y
-----END PGP MESSAGE-----
"""

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.

        let keyData = GenerateKeyData(name: "Hello", email: "hello@word.pgp", password: "HelloWorldPGP", masterKey: KeyData(), subkey: KeyData())
        do {
            let keyRing = try DMSPGPKeyRingFactory(generateKeyData: keyData).keyRing

            print(keyRing.publicKeyRing.armored())
            // -----BEGIN PGP PUBLIC KEY BLOCK-----
            // Comment: Generated by DMSOpenPGP
            //
            // …
            // -----END PGP PUBLIC KEY BLOCK-----
            
            let decryptor = try! DMSPGPDecryptor(armoredMessage: message)
            print(decryptor.encryptedDataDict)

        } catch {
            print(error.localizedDescription)
        }
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

}
